name: main

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Gofmt
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then gofmt -d . && exit 1; fi

      # Populating the modcache with used modules need to be done at some point
      # before running vet, test, build. Run this as a separate step to give
      # an indication of the time it takes to download them.
      - name: Go mod download
        run: go mod download

      - name: Go Vet
        run: go vet .

      - name: Go Build
        run: go build .

      - name: Go Test
        run: go test .

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
