name: Release

on:
  push:
    branches:
    - 'main'
  pull_request:
    - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Install deps
        run: sudo apt install xorg-dev

      - name: Gofmt
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then gofmt -d . && exit 1; fi

      - name: Go mod download
        run: go mod download

      - name: Go Vet
        run: go vet .

      - name: Go Build
        run: go build .

      - name: Go Test
        run: go test .
